# Site settings
title: Open Coalition
email: bekka@open-coalition.org
description: "The Open Coalition is a loose affiliation of organisations, which exists to support collaboration and mobilise action between practitioners and those new to the open space."
baseurl: ""
url: "http://open-coalition.org"

# Build settings
markdown: kramdown
permalink: pretty
